DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT unsigned AUTO_INCREMENT,
  created_at　DATETIME NOT NULL CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL CURRENT_TIMESTAMP ON  UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);
